{% set name = "debug_assert" %}
{% set version = "1.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/foonathan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6d8749eaa6b571b6b53e2355ed0e916a83842cd623ce7e5f65b521ec71b70454

build:
  number: 0
  ignore_run_exports_from:
    # Since this package does not ship any compiled code, we do not need any
    # compatibility with the compiler used at runtime.
    - {{ compiler('cxx') }}

requirements:
  build:
    - cmake
    # debug_assert is header-only but its cmake setup is looking for a compiler to
    # build some test programs (that are not installed.)
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make  # [not win]

test:
  commands:
    - test -f $PREFIX/include/debug_assert.hpp            # [unix]
    - if not exist %LIBRARY_INC%\debug_assert.hpp exit 1  # [win]

about:
  home: https://github.com/foonathan/debug_assert
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: header-only library that provides a very flexible DEBUG_ASSERT() macro
  dev_url: https://github.com/foonathan/debug_assert

extra:
  recipe-maintainers:
    - saraedum
